### ISSUE TITLE
open-notebook (Open Notebook: 0.1.2) and Ollama: how to make it works on ubuntu 24.04?

### ISSUE THREAD

**Issue by JeGoi** [lfnovo/open-notebook#64]
Hi there,
Context:
```
root@localhost:~# cat /etc/os-release 
PRETTY_NAME="Ubuntu 24.04.2 LTS"
NAME="Ubuntu"
VERSION_ID="24.04"
VERSION="24.04.2 LTS (Noble Numbat)"
VERSION_CODENAME=noble
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=noble
LOGO=ubuntu-logo
```
Ollama version:
```
root@localhost:~# ollama --version
ollama version is 0.8.0
```
Ollama settings https://github.com/ollama/ollama/blob/main/docs/faq.md#setting-environment-variables-on-linux
Looks like it is there.
```
root@localhost:~# netstat -tlpnu | grep 11
tcp6       0      0 :::11434                :::*                    LISTEN      44551/ollama
```
Ollama list are there:
```
root@localhost:~# ollama list
NAME                  ID              SIZE      MODIFIED       
llama4:latest         fff25efaabd4    67 GB     39 minutes ago    
deepseek-r1:latest    755ced02ce7b    4.7 GB    44 minutes ago    
qwen3:latest          500a1f067a9f    5.2 GB    44 minutes ago    
gemma3:latest         a2af6cc3eb7f    3.3 GB    45 minutes ago    
llama3.2:latest       a80c4f17acd5    2.0 GB    45 minutes ago 
```
Open-notebook:
```
root@localhost:~# cat docker-compose.yaml 
services:
  surrealdb:
    image: surrealdb/surrealdb:v2
    ports:
      - "8000:8000"
    volumes:
      - surreal_data:/mydata
    command: start --user root --pass root rocksdb:/mydata/mydatabase.db
    pull_policy: always
    user: root

  open_notebook:
    image: lfnovo/open_notebook:latest
    ports:
      - "8080:8502"
    environment:
        - OLLAMA_API_BASE=http://0.0.0.0:11434
        - SURREAL_ADDRESS=surrealdb
        - SURREAL_PORT=8000
        - SURREAL_USER=root
        - SURREAL_PASS=root
        - SURREAL_NAMESPACE=open_notebook
        - SURREAL_DATABASE=open_notebook
    depends_on:
      - surrealdb
    pull_policy: always
    volumes:
      - notebook_data:/app/data

volumes:
  surreal_data:
  notebook_data:
root@localhost:~# docker ps
CONTAINER ID   IMAGE                         COMMAND                  CREATED             STATUS         PORTS                                         NAMES
5949b2d73e97   lfnovo/open_notebook:latest   "uv run streamlit ru…"   8 minutes ago       Up 8 minutes   0.0.0.0:8080->8502/tcp, [::]:8080->8502/tcp   root-open_notebook-1
db6b8661f920   surrealdb/surrealdb:v2        "/surreal start --us…"   About an hour ago   Up 8 minutes   0.0.0.0:8000->8000/tcp, [::]:8000->8000/tcp   root-surrealdb-1
root@localhost:~# docker image ls
REPOSITORY             TAG       IMAGE ID       CREATED        SIZE
surrealdb/surrealdb    v2        29801f708d97   8 days ago     76MB
lfnovo/open_notebook   latest    fd1e5e31ecbf   2 months ago   2.12GB

```
Open notebook GUI is available.
Being able to add Open-NoteBook models, save models (but without choosing a specific MODEL in Ollama list)
```
Configured Models
ollama-embedding (ollama, embedding)
ollama-language (ollama, language)
```
Create a "Notebooks"
Try to add a note, save the note and:
```
requests.exceptions.ConnectionError: HTTPConnectionPool(host='0.0.0.0', port=11434): Max retries exceeded with url: /api/embed (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x78c55a464e60>: Failed to establish a new connection: [Errno 111] Connection refused'))
Traceback:
File "/app/.venv/lib/python3.12/site-packages/streamlit/runtime/fragment.py", line 244, in wrapped_fragment
    result = non_optional_func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/app/.venv/lib/python3.12/site-packages/streamlit/elements/dialog_decorator.py", line 99, in dialog_content
    _ = non_optional_func(*args, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/app/pages/stream_app/note.py", line 25, in add_note
    note.save()
File "/app/open_notebook/domain/base.py", line 143, in save
    EMBEDDING_MODEL.embed(embedding_content)
File "/app/open_notebook/models/embedding_models.py", line 43, in embed
    response = requests.post(
               ^^^^^^^^^^^^^^
File "/app/.venv/lib/python3.12/site-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/app/.venv/lib/python3.12/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/app/.venv/lib/python3.12/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/app/.venv/lib/python3.12/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/app/.venv/lib/python3.12/site-packages/requests/adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
```
It looks like nothing on port 11434 during the request to add a note
```
root@localhost:~# tcpdump -i any port 11434 -v
tcpdump: data link type LINUX_SLL2
tcpdump: listening on any, link-type LINUX_SLL2 (Linux cooked v2), snapshot length 262144 bytes



```
So, I guess it never goes outside of open-notebook.
Ideas?

Note: same on image 0.1.1
Note: Also tried with docker.env file.

**Comment by lfnovo** [comment]
Heym if you are running Open Notebook in a docker container as it looks like you are, then you can't reference to that machine as 0.0.0.0, you need something like: 

```
services:
  surrealdb:
    image: surrealdb/surrealdb:v2
    ports:
      - "8000:8000"
    volumes:
      - surreal_data:/mydata
    command: start --user root --pass root rocksdb:/mydata/mydatabase.db
    pull_policy: always
    user: root

  open_notebook:
    image: lfnovo/open_notebook:latest
    ports:
      - "8080:8502"
    environment:
      - OLLAMA_API_BASE=http://host.docker.internal:11434
      - SURREAL_ADDRESS=surrealdb
      - SURREAL_PORT=8000
      - SURREAL_USER=root
      - SURREAL_PASS=root
      - SURREAL_NAMESPACE=open_notebook
      - SURREAL_DATABASE=open_notebook
    depends_on:
      - surrealdb
    pull_policy: always
    volumes:
      - notebook_data:/app/data
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  surreal_data:
  notebook_data:
```

Let me know if that works for you.

**Comment by lfnovo** [comment]
Changes were on these lines: 

- OLLAMA_API_BASE=http://host.docker.internal:11434
extra_hosts:
      - "host.docker.internal:host-gateway"

**Comment by JeGoi** [comment]
Ok thanks now I have something on Ollama.
But another issue on notebook:
```
KeyError: 'embeddings'
Traceback:
File "/app/.venv/lib/python3.12/site-packages/streamlit/runtime/fragment.py", line 245, in wrapped_fragment
    result = non_optional_func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/app/.venv/lib/python3.12/site-packages/streamlit/elements/dialog_decorator.py", line 99, in dialog_content
    _ = non_optional_func(*args, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/app/pages/stream_app/note.py", line 25, in add_note
    note.save()
File "/app/open_notebook/domain/base.py", line 143, in save
    EMBEDDING_MODEL.embed(embedding_content)
File "/app/open_notebook/models/embedding_models.py", line 47, in embed
    return response.json()["embeddings"][0]
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
```
and a 404 on ollama:
```
Jun 03 00:19:54 localhost ollama[61518]: [GIN] 2025/06/03 - 00:19:54 | 404 |     888.173µs |      172.19.0.3 | POST     "/api/embed"
```


I also have that from the container logs:
```
    if asyncio.get_running_loop().is_running():                                                                                                                                            00:24:30 [0/1785]
       ^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: no running event loop

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/.venv/lib/python3.12/site-packages/streamlit/watcher/local_sources_watcher.py", line 217, in get_module_paths
    potential_paths = extract_paths(module)
                      ^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/streamlit/watcher/local_sources_watcher.py", line 210, in <lambda>
    lambda m: list(m.__path__._path),
                   ^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/torch/_classes.py", line 13, in __getattr__
    proxy = torch._C._get_custom_class_python_wrapper(self.name, attr)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Tried to instantiate class '__path__._path', but it does not exist! Ensure that it is registered via torch::class_
2025-06-03 00:23:48.981 | ERROR    | open_notebook.domain.base:save:172 - Error saving record: 'embeddings'
────────────────────────── Traceback (most recent call last) ───────────────────────────
  /app/.venv/lib/python3.12/site-packages/streamlit/runtime/fragment.py:245 in
  wrapped_fragment

  /app/.venv/lib/python3.12/site-packages/streamlit/elements/dialog_decorator.py:99 in
  dialog_content

  /app/pages/stream_app/note.py:25 in add_note

    22 │   note_content = st.text_area("Content")
    23 │   if st.button("Save", key="add_note"):
    24 │   │   note = Note(title=note_title, content=note_content, note_type="human")
  ❱ 25 │   │   note.save()
    26 │   │   note.add_to_notebook(notebook_id)
    27 │   │   st.rerun()
    28

  /app/open_notebook/domain/base.py:143 in save

    140 │   │   │   │   │   │   │   "No embedding model found. Content will not be sea
    141 │   │   │   │   │   │   )
    142 │   │   │   │   │   data["embedding"] = (
  ❱ 143 │   │   │   │   │   │   EMBEDDING_MODEL.embed(embedding_content)
    144 │   │   │   │   │   │   if EMBEDDING_MODEL
    145 │   │   │   │   │   │   else []
    146 │   │   │   │   │   )

  /app/open_notebook/models/embedding_models.py:47 in embed

     44 │   │   │   f"{self.base_url}/api/embed",
     45 │   │   │   json={"model": self.model_name, "input": [text]},
     46 │   │   )
  ❱  47 │   │   return response.json()["embeddings"][0]
     48
     49
     50 @dataclass
────────────────────────────────────────────────────────────────────────────────────────
────────────────────────────────────────────────────────────────────────────────────────
KeyError: 'embeddings'
2025-06-03 00:15:07.643 Examining the path of torch.classes raised:
Traceback (most recent call last):
  File "/app/.venv/lib/python3.12/site-packages/streamlit/web/bootstrap.py", line 347, in run
    if asyncio.get_running_loop().is_running():
       ^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: no running event loop

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/.venv/lib/python3.12/site-packages/streamlit/watcher/local_sources_watcher.py", line 217, in get_module_paths
    potential_paths = extract_paths(module)
                      ^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/streamlit/watcher/local_sources_watcher.py", line 210, in <lambda>
    lambda m: list(m.__path__._path),
                   ^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/torch/_classes.py", line 13, in __getattr__
    proxy = torch._C._get_custom_class_python_wrapper(self.name, attr)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Tried to instantiate class '__path__._path', but it does not exist! Ensure that it is registered via torch::class_
2025-06-03 00:19:54.031 | ERROR    | open_notebook.domain.base:save:172 - Error saving record: 'embeddings'
```

**Comment by lfnovo** [comment]
What embedding model are you using? have you pulled this model in ollama? 

`ollama pull mxbai-embed-large`

**Comment by JeGoi** [comment]
Thanks for your time and answers.
I wrote the list there: https://github.com/lfnovo/open-notebook/issues/64#issue-3101281014
I remove all models listed previously and add only `mxbai-embed-large`
```
root@localhost:~# ollama list
NAME                        ID              SIZE      MODIFIED      
mxbai-embed-large:latest    468836162de7    669 MB    6 minutes ago 
root@localhost:~# 
```
Stopped the docker-compose, restart it.
Upgrade it to 0.2.1.
Same errors.
(looks like, I am missing something... but what)

**Comment by lfnovo** [comment]
Can you tell me what were you doing before the error? Were you adding a source? Creating a note? Chatting? Searching?

**Comment by JeGoi** [comment]
Sure. Adding a note.
~~I have the same issue by adding a pdf too.~~ new test in progress.

**Comment by JeGoi** [comment]
I also rebuild models from the GUI (in the http://ip:8080/Models)

**Comment by lfnovo** [comment]
@JeGoi  not sure what you mean by rebuild models? And what is this GUI at 8080?

**Comment by lfnovo** [comment]
That's pretty weird. Just tried with my local setup and Ollama using the same model and it works fine. Let's just try something here, can you share your version of ollama and let's also check if the API is up and running (did you run ollama serve?). 

`curl http://localhost:11434/api/version` 

please let me know what comes back.

**Comment by JeGoi** [comment]
Agreed, something is odd.
But I am not able to pinpoint it yet.
Sure:
```
root@localhost:~# curl http://localhost:11434/api/version

{"version":"0.8.0"}root@localhost:~# 
root@localhost:~# ollama -v
ollama version is 0.8.0
```

By rebuild I mean I remove the current models from the ip-for-notebook/Models then recreate them.

**Comment by lfnovo** [comment]
Ok.. got it. I am running 0.9.0 but that shouldn't be the issue. I'll do some further investigation. Just to get something out of the list how are you referencing your Ollama host in the .env file / docker-compose?

**Comment by JeGoi** [comment]
I think it is almost the same as https://github.com/lfnovo/open-notebook/issues/64#issuecomment-2923034989
```
services:
  surrealdb:
    image: surrealdb/surrealdb:v2
    ports:
      - "8000:8000"
    volumes:
      - surreal_data:/mydata
    command: start --user root --pass root rocksdb:/mydata/mydatabase.db
    pull_policy: always
    user: root

  open_notebook:
    image: lfnovo/open_notebook:0.2.1
    ports:
      - "8080:8502"
    environment:
        - OLLAMA_API_BASE=http://host.docker.internal:11434
        - SURREAL_ADDRESS=surrealdb
        - SURREAL_PORT=8000
        - SURREAL_USER=root
        - SURREAL_PASS=root
        - SURREAL_NAMESPACE=open_notebook
        - SURREAL_DATABASE=open_notebook
    depends_on:
      - surrealdb
    pull_policy: always
    volumes:
      - notebook_data:/app/data
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  surreal_data:
  notebook_data:
```

**Comment by lfnovo** [comment]
OK, let's make sure your docker is at least version 20.10: 

`docker version --format '{{.Server.Version}}'` otherwise the host-gateway trick won't work. 

But my biggest hunch is another. Ollama does not listen on 0.0.0.0 by default. Since you are calling it from a different network address, you need to set its environment variable to accept it. 

Here is my ollama.service file to run it as a service on systemctl

```
[Unit]
Description=Ollama Service
After=network-online.target

[Service]
ExecStart=/usr/local/bin/ollama serve
User=ollama
Group=ollama
Restart=always
RestartSec=3
Environment="PATH=..... (redacted)"
Environment="OLLAMA_HOST=0.0.0.0"

[Install]
WantedBy=default.target
```

Pay attention to the OLLAMA_HOST variable being set as 0.0.0.0

In order to ensure this is the case, you can run this docker run command to see if some random docker instance can access ollama. 

```
docker run --rm -it \
  --add-host host.docker.internal:host-gateway \
  ubuntu:latest \
  bash -c "apt-get update && apt-get install -y curl && curl -v http://host.docker.internal:11434"
```

Or you can try to access ollama from another machine in your network via curl or browser.

**Comment by JeGoi** [comment]
As I mentioned there https://github.com/lfnovo/open-notebook/issues/64#issue-3101281014
I used that setting for Ollama and it is listening on 0.0.0.0
Ollama settings https://github.com/ollama/ollama/blob/main/docs/faq.md#setting-environment-variables-on-linux
Looks like it is there.
```
root@localhost:~# netstat -tlpnu | grep 11
tcp6       0      0 :::11434                :::*                    LISTEN      44551/ollama
```

For docker:
```
root@localhost:~# docker version --format '{{.Server.Version}}'
28.2.1
root@localhost:~# docker run --rm -it   --add-host host.docker.internal:host-gateway   ubuntu:latest   bash -c "apt-get update && apt-get install -y curl && curl -v http://host.docker.internal:11434"
[...]
[...]
* Host host.docker.internal:11434 was resolved.
* IPv6: (none)
* IPv4: 172.17.0.1
*   Trying 172.17.0.1:11434...
* Connected to host.docker.internal (172.17.0.1) port 11434
> GET / HTTP/1.1
> Host: host.docker.internal:11434
> User-Agent: curl/8.5.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Content-Type: text/plain; charset=utf-8
< Date: Wed, 04 Jun 2025 18:33:45 GMT
< Content-Length: 17
< 
* Connection #0 to host host.docker.internal left intact
Ollama is running
root@localhost:~
```

Looks fine.

**Comment by lfnovo** [comment]
You are right, I mixed up 2 issues here, sorry. Give me a couple of days as I am rolling out a new release that replace the whole model management logic. Will send you a docker tag to test as soon as it is testable. 

The error seems to be here: 

        response = requests.post(
            f"{self.base_url}/api/embed",
            json={"model": self.model_name, "input": [text]},
        )
        return response.json()["embeddings"][0]

It's not finding the embeddings key in the Ollama response. It's very likely that Ollama is returning an error that I am not properly catching -- the new version will handle this much better. 

In the meantime, you could check the [Ollama logs](https://github.com/ollama/ollama/issues/967) right when the error happens to see if they are complaining about something

We can also see if an error shows up in the terminal

```bash
curl -X POST http://ollama-ip:11434/api/embed \
-H "Content-Type: application/json" \
-d '{"model": "mxbai-embed-large", "input": ["This is an example text for embedding"]}'
```

**Comment by JeGoi** [comment]
No worries.
For ollama, I also wrote it in the first post, it hasn't change since then:
```
Jun 04 21:16:07 localhost ollama[61518]: [GIN] 2025/06/04 - 21:16:07 | 404 |    1.558654ms |      172.19.0.3 | POST     "/api/embed"
```
OLLAMA_DEBUG="1" is set on the service.
```
  GNU nano 7.2                                                                /etc/systemd/system/.#ollama.service64671a11c03d05c7 *                                                                        
[Unit]
Description=Ollama Service
After=network-online.target

[Service]
ExecStart=/usr/local/bin/ollama serve
User=ollama
Group=ollama
Restart=always
RestartSec=3
Environment="PATH=/root/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin"
Environment="OLLAMA_DEBUG=1"

[Install]
WantedBy=default.target
```

No GPU, it is a test machine:
```
Jun 04 21:19:42 localhost ollama[85093]: time=2025-06-04T21:19:42.532Z level=INFO source=gpu.go:377 msg="no compatible GPUs were discovered"
Jun 04 21:19:42 localhost ollama[85093]: time=2025-06-04T21:19:42.532Z level=INFO source=types.go:130 msg="inference compute" id=0 library=cpu variant="" compute="" driver=0.0 name="" total="15.6 GiB" available="9.7 GiB"
```

**Comment by lfnovo** [comment]
Got it.. 

Jun 04 21:16:07 localhost ollama[61518]: [GIN] 2025/06/04 - 21:16:07 | 404 |    1.558654ms |      172.19.0.3 | POST     "/api/embed"

404 is not found. 

I saw this [issue](https://github.com/ollama/ollama/issues/6730) but that is for older version of ollama. How about you try to upgrade it to the latest version just to make sure?

**Comment by JeGoi** [comment]
Bump to 0.9.0.
Re-add mxbai-embed-large
```
root@localhost:~# ollama -v
ollama version is 0.9.0
root@localhost:~# ollama list
NAME                        ID              SIZE      MODIFIED       
mxbai-embed-large:latest    468836162de7    669 MB    36 minutes ago  
```
Clean the DB.
Clean docker.
Restart everything.
Write a note in a new Notebook
```
KeyError: 'embeddings'
Traceback:
File "/app/.venv/lib/python3.12/site-packages/streamlit/runtime/fragment.py", line 245, in wrapped_fragment
    result = non_optional_func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/app/.venv/lib/python3.12/site-packages/streamlit/elements/dialog_decorator.py", line 99, in dialog_content
    _ = non_optional_func(*args, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/app/pages/stream_app/note.py", line 25, in add_note
    note.save()
File "/app/open_notebook/domain/base.py", line 143, in save
    EMBEDDING_MODEL.embed(embedding_content)
File "/app/open_notebook/models/embedding_models.py", line 47, in embed
    return response.json()["embeddings"][0]
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
```

**Comment by lfnovo** [comment]
OK.. let's do just one more thing. Can you stop your local ollama and add it to your  docker compose, like this? 

```
  ollama:
    container_name: ollama
    pull_policy: always
    tty: true
    restart: unless-stopped
    image: ollama/ollama:latest
    ports:
      - 11434:11434
```

Change the URL on the .env file to point to http://ollama and let's give it a shot. 

At this point I am pretty convinced this is an issue with Ollama running on 24.04 having read their threads on Reddit.

**Comment by JeGoi** [comment]
docker-compose:
```
services:
  ollama:
    container_name: ollama
    pull_policy: always
    tty: true
    restart: unless-stopped
    image: ollama/ollama:latest
    ports:
      - 11434:11434
    volumes:
      - ollama_data:/root/.ollama
    user: root

  surrealdb:
    image: surrealdb/surrealdb:v2
    ports:
      - "8000:8000"
    volumes:
      - surreal_data:/mydata
    command: start --user root --pass root rocksdb:/mydata/mydatabase.db
    pull_policy: always
    user: root

  open_notebook:
    image: lfnovo/open_notebook:0.2.1
    ports:
      - "8080:8502"
    environment:
        - OLLAMA_API_BASE=http://ollama:11434
        - SURREAL_ADDRESS=surrealdb
        - SURREAL_PORT=8000
        - SURREAL_USER=root
        - SURREAL_PASS=root
        - SURREAL_NAMESPACE=open_notebook
        - SURREAL_DATABASE=open_notebook
    #env_file:
    #  - ./docker.env
    depends_on:
      - surrealdb
    pull_policy: always
    volumes:
      - notebook_data:/app/data
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  surreal_data:
  notebook_data:
  ollama_data:
```

**NOTE**: that without the port in OLLAMA_API_BASE, I have an error port 80 something unreachable.

Then clean, prune, remove volumes.
Then docker compose up -d
Then in ollama container, I added the 
```
root@localhost:~# docker exec -ti  ollama /bin/bash
root@f74ac91b5123:/# ollama pull mxbai-embed-large
pulling manifest 
pulling 819c2adf5ce6: 100% ▕███████████████████████████████████████▏ 669 MB                         
pulling c71d239df917: 100% ▕███████████████████████████████████████▏  11 KB                         
pulling b837481ff855: 100% ▕███████████████████████████████████████▏   16 B                         
pulling 38badd946f91: 100% ▕███████████████████████████████████████▏  408 B                         
verifying sha256 digest 
writing manifest 
success 
```
Then creating Models, run several time update de the DB (even on a fresh install), then create a notebook, then write a note, then try to save the note and :
```
KeyError: 'embeddings'
Traceback:
File "/app/.venv/lib/python3.12/site-packages/streamlit/runtime/fragment.py", line 245, in wrapped_fragment
    result = non_optional_func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/app/.venv/lib/python3.12/site-packages/streamlit/elements/dialog_decorator.py", line 99, in dialog_content
    _ = non_optional_func(*args, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/app/pages/stream_app/note.py", line 25, in add_note
    note.save()
File "/app/open_notebook/domain/base.py", line 143, in save
    EMBEDDING_MODEL.embed(embedding_content)
File "/app/open_notebook/models/embedding_models.py", line 47, in embed
    return response.json()["embeddings"][0]
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
```
Thanks for your time!
